name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: bernardo140109
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
